export const CONTACT_FORM_LOAD_FORM = 'CONTACT_FORM_LOAD_FORM';
export const CONTACT_FORM_ADD_DEFAULT_FIELD = 'CONTACT_FORM_ADD_DEFAULT_FIELD';
export const CONTACT_FORM_REMOVE_FIELD = 'CONTACT_FORM_REMOVE_FIELD';
export const CONTACT_FORM_CLEAR_FORM = 'CONTACT_FORM_CLEAR_FORM';
